sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: i5wxYL8B4cyGBLaP3qxBYoAb7W7dW+HbIceFy5jL3qDGWUEqy9vIjYlrt1d/2Ygy1ofS2VuNYuxnDS7ar2Qu1S0Eob/68snB6bMsVcZ0tUQ8shOt8RdRf4IJwjOj6SAjfXc1ui3hvherOg6oToIRIOYa33ZfJwjrtpRecZ3Wnv++2dMr6A66Zni6ya5vWXf7U4anDHvH2fZvXZr3kR7pYn5YP7mdbQOmWKPFq7iV4qS5wSrEjkf383O0lPYsd8A49tKj5CxEf4d78+WwVBOd0TpZ3U+GUN8kft4FSBaDZmygNsmQpiX0Jt72xYTzypHv1CwQd/dcHlSQ0bDne7F2Blp4WSJcpLvC4b5sjU38MK2Wb3TdRVXbvYJWZMiV4oY5uuCPy9YygLP1M0Ev3dO7BaFfKuZN9nz/gP8jRSjC4uDHP0rWSeiI+LnsR5L2pSwqpG8AcmHh/YtjUHw58ypmVeuT01tOhs99JU/EgZsd3cEgBqaozx0Q49OBglgBQMBhrXEr41FBt8lq7Ro9t3ZEyWKCy4M5XzbUny28IC18hputVLFZGTbLat7ednAQxGE5ThRstPdurQ3IbR87NZqZtE6LQBHrwl2K0efs7jCu/ijKK0cOEdQQulaZ1YebdTg/CXbNW17pp3MMnvhQ8FD/qTmF64FOWP9Aetd+352X4fs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Recollections-of-the-Private-Life-of-Napoleon-Volume-12_3579
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy